name: VPN
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 9999

    steps:

    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ 
[drive_to_drive]
type = drive
client_id = 626138316248-bttiisuo742slu37ometqmdjtga6m2kv.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AeTM1if89j3eEtOFH9hWgd2CLFN3bqLGh60TE8KsH5IZ-5W-FyMmU7mPmE3tJM3WlBV5TZgWUfXYr3oavPDKCbJpE5uSnCtY95y0_agL7tq0rE_shw9VlTCD6PbE81jIdFlhSqz2gv-0iGTUkXvrcr8oUnpTaCgYKAeASARASFQHWtWOmXPnthmnXKrCjyU0ys-Xm5A0163","token_type":"Bearer","refresh_token":"1//0grIV_7YWJebDCgYIARAAGBASNwF-L9IrwU-ydbCKSBuXGyynEDtgUknUX7cJ6rpWiGAG2rhDo_ftGdHHgAO1wTuw_gxvbWe_bF8","expiry":"2022-11-07T13:33:11.923773335+06:30"}
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://oauth2.googleapis.com/token
team_drive = 0AJR63Qu_FR8hUk9PVA
root_folder_id = }}
      
    - name: Download Autorclone
      run: wget https://www.dropbox.com/s/hm5an8z5fois7zu/AutoRcloneSync.zip && unzip "AutoRcloneSync.zip"
    
    - name: Show File Location
      run: pwd
      
    - name: Find File Location
      run: find ./ -name AutoRcloneSync.zip
        
    - name: See config File
      run: |
        cat ./home/runner/.config/rclone/rclone.conf
    
    - name: Into Autorclone amd Python Run
      working-directory: ./AutoRcloneSync
      run: |
          pwd
          python3 autorclone.py --sync -s 0AJR63Qu_FR8hUk9PVA -d 0AIKstA9CskDFUk9PVA --sa-start-id 1 --sa-end-id 50
                
    - name: Into Autorclone amd Python Run (2)
      working-directory: ./AutoRcloneSync
      run: |
          pwd
          python3 autorclone.py --sync -s 0AJR63Qu_FR8hUk9PVA -d 0AIKstA9CskDFUk9PVA --sa-start-id 51 --sa-end-id 100
